{{- if .Values.appSecrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lakedeepdiver.fullname" . }}-app
  labels:
    {{- include "lakedeepdiver.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.appSecrets.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}