apiVersion: v2
name: lakedeepdiver
description: LakeDeepDiver - Iceberg maintenance control plane (Rails 8 + Solid Queue)
type: application
version: 0.1.0 # x-release-please-version
appVersion: "0.1.0" # x-release-please-version
home: https://github.com/maltzsama/lakedeepdiver
keywords:
  - iceberg
  - trino
  - rails
maintainers:
  - name: LakeDeepDiver team