apiVersion: v1
kind: Service
metadata:
  name: {{ include "deepdiver.fullname" . }}
  labels:
    {{- include "deepdiver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "deepdiver.webSelector" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http